[www]
; L'utilisateur Linux qui fera tourner WordPress
user = www-data
group = www-data

; Très important : On écoute sur le port 9000 pour que Nginx puisse nous parler
listen = 0.0.0.0:9000

; Paramètres de gestion de la mémoire (requis par PHP-FPM)
pm = dynamic
pm.max_children = 25
pm.start_servers = 5
pm.min_spare_servers = 1
pm.max_spare_servers = 10