events {
    # Ce bloc est obligatoire, même vide
}

http {
    # Inclusion des types MIME (pour que le CSS et les images s'affichent correctement)
    include /etc/nginx/mime.types;
    
    server {
        # On écoute EXCLUSIVEMENT sur le port 443 (HTTPS)
        listen 443 ssl;
        listen [::]:443 ssl;
        
        # Le nom de domaine (qui sera lu depuis l'environnement)
        server_name inception.42.fr;

        # Les certificats de sécurité qu'on va générer dans le Dockerfile
        ssl_certificate /etc/ssl/certs/inception.crt;
        ssl_certificate_key /etc/ssl/private/inception.key;

        # Exigence stricte du sujet : Uniquement TLSv1.2 et TLSv1.3
        ssl_protocols TLSv1.2 TLSv1.3;

        # Le dossier où Nginx va chercher les fichiers
        root /var/www/wordpress;
        
        # L'ordre de priorité des fichiers à lire
        index index.php index.html;

        # Règle de base : Si le fichier n'existe pas, on redirige vers WordPress
        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        # Règle pour les fichiers PHP : On les envoie au conteneur WordPress
        location ~ \.php$ {
            # On sépare le nom du script de ses arguments
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            
            # On envoie la requête au port 9000 du conteneur "wordpress"
            fastcgi_pass wordpress:9000;
            
            # Le fichier par défaut
            fastcgi_index index.php;
            
            # Inclusion des paramètres standard de FastCGI
            include fastcgi_params;
            
            # On indique précisément le chemin du fichier à lire
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }
}